### ISSUE TITLE
Add settings to control request timeout

### ISSUE THREAD

**Issue by wong2** [alchemyplatform/alchemy-sdk-js#167]
When using alchemy-sdk in my project, sometimes the call just stuck there for a long time, I'd like a setting for timeout seconds, so I can have better control on it with timeout & maxRetries

**Comment by thebrianchen** [comment]
@wong2 thanks for the feature request! Are you primarily using the NFT APIs or the core json-rpc APIs?

**Comment by wong2** [comment]
NFT APIs

**Comment by wong2** [comment]
NFT APIs

**Comment by wong2** [comment]
NFT APIs

**Comment by ef3n9r98** [comment]
Hey @thebrianchen, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](www.openq.dev). 

Thanks!

**Comment by Abbaskt** [comment]
[Axios documentation](https://axios-http.com/docs/req_config), according to the documentation a `timeout` variable in the request config which can be set in the following way, `timeout: <desired timeout>`.
This line can be added in the axios request function `sendAxiosRequest` where the config is initialized [here](https://github.com/alchemyplatform/alchemy-sdk-js/blob/main/src/util/sendRest.ts#L23)
This can also be added while initializing the SDK or even while calling a specific API (can be included as an argument), instead of having a default static value.

Would be happy to work on this if required.

**Comment by thebrianchen** [comment]
@Abbaskt We'd love to welcome any PRs you may have time for. Otherwise, we'll likely to get to this when it's more prioritized. Thanks!
