### ISSUE TITLE
Alchemy NFT API does not return all NFTs

### ISSUE THREAD

**Issue by namnguyen2496** [alchemyplatform/alchemy-sdk-js#259]
### [REQUIRED] Environment

- Browser version: Version 109.0.5414.119 (Official Build) (arm64)
- Alchemy SDK version: 2.41

### [REQUIRED] Describe the problem
I cannot see some NFTs when querying for NFTs owned by an address

#### How to reproduce:
```
const address = "0x07670Dd0d0d00Ed6ec47cD4073c7ad5DdDa32405"
const alchemyNFTs = await AlchemyClient.getNFTsOwnedByAddress(address);
const boredApe = alchemyNFTs.filter(nft => nft.contractAddress.toLowerCase() === "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d".toLowerCase() && nft.tokenId === "8871");
console.log(boredApe); // Should have something, but is empty.
```

The NFT is in this wallet: https://zapper.fi/nft/ethereum/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/8871

**Comment by thebrianchen** [comment]
@namnguyen2496 are you using the NFT API in the SDK? The NFT does appear from the REST API: [link](https://eth-mainnet.g.alchemy.com/nft/v2/demo/getNFTs?owner=0x07670Dd0d0d00Ed6ec47cD4073c7ad5DdDa32405&contractAddresses%5B%5D=0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d)

My guess is that you are filtering by `tokenId` as an integer string. However, the tokenId is returned as a hex string, which might be why your filter accidentally filters it out. You'll have to filter by `tokenId="0x00000000000000000000000000000000000000000000000000000000000022a7"` instead.

I'm going to mark this issue as closed since the NFT is returned, but feel free to ask any other questions you might have!

**Comment by namnguyen2496** [comment]
Hi, I used the SDK (as I mentioned in my post)

This is the payload I got:

```
  {
    contractAddress: '0xd0ca41e0098ffa698d9a4d33b61006a490678d94',
    tokenId: '89',
    name: 'MPLC | Emily Xie | #89',
    collection: 'MPLC5',
    fullImageUrl: 'https://bh.mypinata.cloud/ipfs/QmdBJtqc9ZkVVyrJXL2FJw5HCKK462K4n5w62snnTDmxkh',
    thumbnailUrl: 'https://res.cloudinary.com/alchemyapi/image/upload/thumbnail/eth-mainnet/f0d1defb728ac61b33d33668f5b16adc',
    timeLastUpdated: 1675270883690
  },
  {
    contractAddress: '0xd5bdb5165fc91165eb3195327fecc71269470227',
    tokenId: '79',
    name: '',
    collection: 'CTQI Community',
    fullImageUrl: null,
    thumbnailUrl: null,
    timeLastUpdated: 1675282391948
  }
```

**Comment by namnguyen2496** [comment]
@thebrianchen found more NFTs by calling your API directly. But I couldn't quite figure out how to get the same information with the SDK.

**Comment by thebrianchen** [comment]
@namnguyen2496 This is the method you are looking for: https://docs.alchemy.com/reference/sdk-getnfts
