### ISSUE TITLE
Alchemy SDK Import error while running within a Service Worker

### ISSUE THREAD

**Issue by mariano-altieri** [alchemyplatform/alchemy-sdk-js#325]
### [REQUIRED] Environment
- Browser version: Google Chrome v.112.0.5615.49 
- Alchemy SDK version: v2.8.1"

### [REQUIRED] Describe the problem
While developing a Crypto Wallet as a Chrome Extension, we moved all logic regarding wallet accounts creation and token transactions (basically any interaction with Alchemy) to the `background script`. By doing so we uncovered a JS error, visible in Chrome Console:
<img width="1145" alt="Screen Shot 2023-05-15 at 16 28 18" src="https://github.com/alchemyplatform/alchemy-sdk-js/assets/5373548/90bef02d-f495-47b5-910e-57a2608deabd">

if you follow the first sdk code link displayed by console, you will be redirected to:
```javascript
getProvider() {
        return this._baseAlchemyProvider || (this._baseAlchemyProvider = (()=>D(this, void 0, void 0, function*() {
            const {AlchemyProvider: e} = yield mo(()=>import("./alchemy-provider-f7c978b3.js").then(r=>r.a), []);
            return new e(this)
        }))()),
        this._baseAlchemyProvider
    }
```    

You can see there the `import(...)` causing the issue. If you monkey-patch this, by including the `AlchemyProvider` as a regular import and removing the asynchronous part of your logic, it works:

```javascript
if (!this._baseAlchemyProvider) {
        this._baseAlchemyProvider = new AlchemyProvider(this);
}
```

#### How to reproduce:
To reproduce,  i believe simply trying to create the Alchemy SDK Wallet in a service worker context should suffice.

#### Relevant code or sample repro:
```
export class AlchemyApi {
    protected apiKey: string;
    protected network: Network;
    protected alchemy: Alchemy;

    constructor(network = Network.MATIC_MAINNET) {
        this.apiKey = ALCHEMY_KEY;
        this.network = network;

        this.alchemy = new Alchemy({
            apiKey: this.apiKey,
            network: this.network,
        });
    }

    getInstance(): Alchemy {
        return this.alchemy;
    }
}
```
```
import { Wallet } from 'alchemy-sdk';

export class Account extends Wallet {
    protected tokens: TOKEN_CONTRACT_ADDRESSES[] = [];
    protected alchemy;

    constructor(privateKey = '') {
        const privKey = privateKey || Account.createRandom().privateKey;
        const provider = new AlchemyApi().getInstance();

        super(privKey, provider);
        this.alchemy = provider;
    }
    ....

Any help or advice on how to work around this would be greatly appreciated. Thank you!

**Comment by thebrianchen** [comment]
@mariano-altieri We currently use the `import()` syntax to dynamically import the provider code since it's a large dependency. Using a regular import ahead of time would cause the package size to be bloated for people only not using provider-level methods, so unfortunately, we cannot change this.

The inability to import inside a service worker seems to be a longstanding bug with Chrome extensions: ([github link](https://github.com/w3c/ServiceWorker/issues/1585),  [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1198822)). Perhaps one of the workarounds in the thread can work for you!

**Comment by thebrianchen** [comment]
@mariano-altieri We currently use the `import()` syntax to dynamically import the provider code since it's a large dependency. Using a regular import ahead of time would cause the package size to be bloated for people only not using provider-level methods, so unfortunately, we cannot change this.

The inability to import inside a service worker seems to be a longstanding bug with Chrome extensions: ([github link](https://github.com/w3c/ServiceWorker/issues/1585),  [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1198822)). Perhaps one of the workarounds in the thread can work for you!
