### ISSUE TITLE
FR: Use ethers v6

### ISSUE THREAD

**Issue by SKYBITDev3** [alchemyplatform/alchemy-sdk-js#378]
Update your code to use ethers v6, which was released over 8 months ago and is now at v6.8.0.

**Comment by thebrianchen** [comment]
@SKYBITDev3 Thanks for filing an issue! As it stands, ethers v6 does not have the same adoption as ethers v5. Since it will be a breaking change for the SDK to upgrade to v6, we will not undertake this until we receive more developer demand. I'll leave this issue open to track. 

Was there any particular feature on ethers v6 that you were looking for?

**Comment by SKYBITDev3** [comment]
No particular feature, but it's inconvenient to have to rewrite ethers v6 code that we already have down to ethers v5 code just to be able to use alchemy SDK, so we'll consider other options in the meantime.
