### ISSUE TITLE
coherent raw metadata typings

### ISSUE THREAD

**Issue by Jo-Chris** [alchemyplatform/alchemy-sdk-js#381]
### [REQUIRED] Environment

- Browser version: NodeJS
- Alchemy SDK version: 2.10.1

### [REQUIRED] Describe the problem
While using `nft.getNftsForOwner(address)`

```
for ERC721 NFTS: ownedNfts -> rawMetadata -> name
for ERC1155 NFTS: ownedNfts -> rawMetadata -> Name
```

same goes for rawMetadata.description and rawMetadata.Description

#### How to reproduce:

call `nft.getNftsForOwner(address)` with an address holding an ERC721 and 1155 and check the
rawMetadata object

#### Relevant code or sample repro:

```
export interface NftMetadata extends Record<string, any> {
    name?: string;             <--- lowercase
    description?: string;      <--- lowercase
    image?: string;
    external_url?: string;
    background_color?: string;
    attributes?: Array<Record<string, any>>;
}

export interface Nft extends BaseNft {
    contract: NftContract;
    title: string;
    description: string;
    timeLastUpdated: string;
    metadataError: string | undefined;
    rawMetadata: NftMetadata | undefined;
    tokenUri: TokenUri | undefined;
    media: Media[];
    spamInfo?: SpamInfo;
    acquiredAt?: AcquiredAt;
}
```

**Comment by thebrianchen** [comment]
@Jo-Chris The `name` and `description` fields on the `NftMetadata` interface represent Alchemy's best effort at extracting the name and fields from the raw metadata. the `rawMetadata` field holds the raw JSON metadata blob that the `tokenUri` on the NFT contract points to. We have no control over what those raw fields are, but we've standardized the response types for our properties.

I'm going to mark this issue as closed since it's working as intended, but feel free to ask any other questions you may have!
